name: Deploy Angular
on: [push, pull_request]

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
