name: Deploy Angular
on: [push, pull_request]

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Use Node 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:prod
      - name: Copy 404 from index
        id: index
        uses: juliangruber/read-file-action@v1
        with:
          path: ./docs/index.html
      - name: Paste 404 page 
        uses: DamianReeves/write-file-action@v1.0
        with: 
          path: ./docs/404.html
          contents: ${{ steps.index.outputs.content }}
          write-mode: overwrite
#       - name: Archive build
#         if: success()
#         uses: actions/upload-artifact@v1
#         with:
#           name: deploy_docs
#           path: docs
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#       - name: Download build
#         uses: actions/download-artifact@v1
#         with:
#           name: deploy_docs
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs

      
